#!/usr/bin/env python3
import sys
import os
from ASTDiff import ASTDiff
oldFileName = sys.argv[1]
newFileName = sys.argv[2]
os.system("gumtree parse " + oldFileName + " > ASTbefore.json")
os.system("gumtree parse " + newFileName + " > ASTafter.json")
os.system("gumtree diff " + oldFileName + " " + newFileName + " > diffscript.txt")

astDiff = ASTDiff(oldFileName, newFileName)
# print(astDiff.getDiffTreeNode())
astDiff.outputChangedNode()
